source: app
destination: app/_site

# Site settings
title: Jekyll Polymer Theme
author: Julia Ebert
author_website: http://juliaebert.com
email: julia@juliaebert.com
description: > # this means to ignore newlines until "baseurl:"
  This is a material design theme for Polymer using Google's Polymer library. It's still an early draft, so be nice.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mmsportservice.com" # the base hostname & protocol for your site
twitter_username: ''
github_username:  msports
disqus_shortname: msports
google_analytics: UA-54476418-1

# Pagination
paginate: 5
paginate_path: "page:num"
excerpt_separator: <!--more-->

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
